### ISSUE TITLE
Fail validate iTunes connect

### ISSUE THREAD

**Issue by skull-man** [hyperoslo/Lightbox#109]
Hello! Faced the problem of checking the archive when it was published in itunes. The fact is that the policy of the apple prohibits the use of built-in frameworks. I removed the hue from the framework, hooked it up as a separate framework, and the project was tested. Make changes please.

Sorry, I'm using google translate =)

**Comment by onmyway133** [comment]
@skull-man Hi, have you tried this https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos?

**Comment by ikesyo** [comment]
The problem is that using `carthage copy-frameworks` in a framework target. Nested frameworks (embedding frameworks in other frameworks) is rejected by App Store submission validation. So you maintainers should remove the build phase from this framework tatget, and the framework users should embed both the framework and Hue.framework in their application (flattening instead of nesting).

**Comment by onmyway133** [comment]
@ikesyo Hi, I see, thanks
@skull-man Hi, in the mean time, we can use `--no-build` with Carthage, and just drag those projects into your workspace
