### ISSUE TITLE
Landscape mode swipe bug

### ISSUE THREAD

**Issue by bugs33ker** [hyperoslo/Lightbox#111]
Hello,
I get a weird bug when in landscape mode and swiping up or down. The view becomes messed up and layouts are wrong.

**Comment by onmyway133** [comment]
@bugs33ker Hi, can you show us the screenshot?

**Comment by bugs33ker** [comment]
![img_0275](https://cloud.githubusercontent.com/assets/25406260/26194776/efdf3324-3bd2-11e7-8f1b-f074f9978160.PNG)
![img_0276](https://cloud.githubusercontent.com/assets/25406260/26194775/efa917da-3bd2-11e7-96b5-65ab64455fd0.PNG)

**Comment by ghecho** [comment]
Yes, I got that too. The issue arises when you:

1. Present the Lightbox Controller
2. Rotate the device
3. Close the Lightbox Controller

You can "fix" the issue by doing the steps in reverse order.

**Comment by onmyway133** [comment]
@bugs33ker @ghecho Hi, what version of Lightbox are you using? Can you show us the commit? And can you try master `pod 'Lightbox', git: 'https://github.com/hyperoslo/Lightbox'`?

**Comment by ghecho** [comment]
I was using version 1.0.0.

I tried:

- `pod 'Lightbox', git: 'https://github.com/hyperoslo/Lightbox'`
- `pod 'Lightbox', :git => 'https://github.com/hyperoslo/Lightbox.git'`
- `pod 'Lightbox', :git => 'https://github.com/hyperoslo/Lightbox.git', :branch => 'master'`

and in all cases it said `Installing Lightbox 1.0.0 (was 1.0.0)` when I ran `pod update`

But I assume that even though I was using version 1.0.0 It was the tagged commit and with this it changed to the master branch and since it doesn't have a newer branch it shows 1.0.0 also.

Anyway, when I use the master branch the issue is resolved. Thanks for your help. 😃
