### ISSUE TITLE
Carthage build error

### ISSUE THREAD

**Issue by nitrag** [hyperoslo/Lightbox#165]
```
*** Checking out Lightbox at "b26ee135bc89494a8cf9c7c30dbea2c42589c03a"
*** xcodebuild output can be found in ...
*** Building scheme "Hue-iOS" in Hue.xcodeproj
*** Building scheme "Lightbox-iOS" in Lightbox.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /*/Carthage/Checkouts/Lightbox/Lightbox.xcodeproj -scheme Lightbox-iOS -configuration Release -derivedDataPath /Users/*/Library/Caches/org.carthage.CarthageKit/DerivedData/9.1_9B55/Lightbox/1.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /*/Carthage/Checkouts/Lightbox)
```

```
/*/Carthage/Checkouts/Lightbox/Source/LightboxConfig.swift:2:8: error: module file's minimum deployment target is ios9.0 v9.0: /*/Carthage/Checkouts/Lightbox/Carthage/Build/iOS/Hue.framework/Modules/Hue.swiftmodule/arm64.swiftmodule
import Hue
       ^

** ARCHIVE FAILED **


The following build commands failed:
        CompileSwift normal armv7
        CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
        CompileSwift normal arm64
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(4 failures)
```

XCode 9.1

**Comment by onmyway133** [comment]
@nitrag Hi, the log says "module file's minimum deployment target is ios9.0 v9.0". Can you check your minimum deployment target?

**Comment by wousser** [comment]
I've set the minimum deployment target to ios1.0 and can reproduce this error.

**Comment by wousser** [comment]
If you add all dependencies in your Cartfile the build will succeed.

`#Lightbox
github "hyperoslo/Cache"
github "hyperoslo/Hue"
github "hyperoslo/Imaginary"
github "hyperoslo/Lightbox"
`

**Comment by abbana** [comment]
Hi,

thanks for responding.

I have copied the Source in my project, but still I have issues

*2018-01-23 07:46:57.449890+0000 Regional2[2380:1173405] [] <<<<
AVOutputDeviceDiscoverySession (FigRouteDiscoverer) >>>>
-[AVFigRouteDiscovererOutputDeviceDiscoverySessionImpl
outputDeviceDiscoverySessionDidChangeDiscoveryMode:]: Setting device
discovery mode to DiscoveryMode_Presence (client: Regional2)*

*2018-01-23 07:47:16.475952+0000 Regional2[2380:1173405] [] <<<<
AVOutputDeviceDiscoverySession (FigRouteDiscoverer) >>>>
-[AVFigRouteDiscovererOutputDeviceDiscoverySessionImpl
outputDeviceDiscoverySessionDidChangeDiscoveryMode:]: Setting device
discovery mode to DiscoveryMode_None (client: Regional2)*

*2018-01-23 07:47:17.021001+0000 Regional2[2380:1173405] [Default]
MPMediaControlsRemoteViewController Dismissing because view service
terminated*



Only way to make this working is to use Cartfile?

**Comment by abbana** [comment]
*2018-01-23 08:37:11.654455+0000 Regional2[5965:3576191] [ImageManager]
Unable to load image data, /var/mobile/Media/DCIM/102APPLE/IMG_2550.JPG*

**Comment by onmyway133** [comment]
@abbana @nitrag Hi, can you check the new release https://github.com/hyperoslo/Lightbox/releases/tag/2.3.0 ?
